### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hkva** [hkva/medkit#1]
* [ ] Scan for debug symbols embedded in ELF executables
* [ ] IDA byte pattern scanning
* [ ] "Code" byte pattern scanning
* [ ] External versions of all current functions
* [ ] C++ Wrapper
